### ISSUE TITLE
Shine effect does not work in Wow Classic

### ISSUE THREAD

**Issue by michaelnpsp** [Stanzilla/LibCustomGlow#13]
Shine effect is not visible because the Interface\Artifacts\Artifacts texture is different in Classic and the shine particle image is placed in a different place. 
It can be fixed changing the texture coordinates in line 384 for classic.
Correct texcoords:
`{0.0146484375,0.1201171875,0.2070312500,0.3125000000}`

**Comment by Azilroka** [comment]
Yea I used the original texture as it is the same in all versions of WoW and will not need to be tweaked if Blizzard decides to yolo the newer texture in.
