### ISSUE TITLE
Load Order Issue

### ISSUE THREAD

**Issue by StormFX** [Stanzilla/LibCustomGlow#27]
Currently, if Masque is loaded after an add-on that uses LCG but does NOT support Masque, it can cause issues with the glows not being skinned properly for add-ons that do support Masque. LCG has Masque set as an OptDep, but is usually embedded whic prevents it from being properly preloaded. Can you have LCG force-load Masque? Eg:

Line 13 from:
```lua
local Masque =  LibStub("Masque", true)
```
to
```lua
local Masque = C_AddOns.LoadAddOn("Masque") and LibStub("Masque", true)
```

That is unless you have a better solution. :P

**Comment by Stanzilla** [comment]
Fixed in https://github.com/DeadlyBossMods/DeadlyBossMods/issues/1340
